### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by DAW93** [gvellut/FreehandRasterGeoreferencer#1]
Hi,
When I try to install the plugin, I get the following error message: "This plugin is broken
No module named ui_freehandrastergeoreferencer". Is there a fix for this?
Thanks,
Duncan

**Comment by gvellut** [comment]
You need to compile the resources and the UI definitions. Launch build.sh (on UNIX) or build.bat (on Windows) from the plugin directory.

**Comment by DAW93** [comment]
Hey, thanks for the reply. I tried launching the build.bat file but I am unfortunately still getting the same error. Not sure where I am going wrong.

**Comment by Dkrav-UA** [comment]
Get this plugin from QGIS\Modules.
Or, if you want to compile it, make sure you have path to pyuic4 and pyrcc4 in your PATH.

**Comment by gvellut** [comment]
Like Dkrav-UA is saying, I have uploaded the plugin into the QGIS plugin registry, so it is easier to install.
You can open the "Plugins" > "Manage and install plugin" dialog and look for the "Freehand Raster Georerencer" plugin.

**Comment by DAW93** [comment]
Fantastic thanks! Nice job, it's a great plugin.
