### ISSUE TITLE
Predefined scale.

### ISSUE THREAD

**Issue by Dkrav-UA** [gvellut/FreehandRasterGeoreferencer#10]
It would be nice to add feature to set scale of image on opening. Some times much faster to set scale when you know scale on paper and dpi.

**Comment by Dkrav-UA** [comment]
Made some improvements to class ScaleRasterMapTool. 
Now when right mouse button is  pressed you can manually insert scale. Formulas can be used.
For example, 30/(96/2.54) would be calculated. 30 is scale in meters, 96 is dpi of image.

    def canvasPressEvent(self, e):
        pressed_button = e.button()
        if pressed_button == 1:
            self.startPoint = e.pos()
            self.endPoint = self.startPoint
            self.isEmittingPoint = True
            self.height = float(self.canvas.height())
            self.width = float(self.canvas.width())

            modifiers = QApplication.keyboardModifiers()
            self.isKeepRelativeScale = bool(modifiers & Qt.ControlModifier)

            self.isLayerVisible = self.iface.legendInterface().isLayerVisible(
                self.layer)
            self.iface.legendInterface().setLayerVisible(self.layer, False)

            scaling = self.computeScaling()
            self.showScaling(*scaling)

    def canvasReleaseEvent(self, e):
        from PyQt4.QtGui import QInputDialog, QMessageBox

        def is_formula(text):
            for c in text:
                if c not in u'+- 1234567890./*()':
                    print '{} not a formula. char: {}'.format(text, c)
                    return False
            print '{} is a formula'.format(text)
            return True


        pressed_button = e.button()
        if pressed_button == 1:
            self.isEmittingPoint = False

            self.rubberBandExtent.reset(QGis.Line)
            self.rasterShadow.reset()

            xScale, yScale = self.computeScaling()
            self.layer.setScale(xScale * self.layer.xScale,
                                yScale * self.layer.yScale)

            self.iface.legendInterface().setLayerVisible(self.layer,
                                                         self.isLayerVisible)
            self.layer.repaint()

            self.layer.commitTransformParameters()
        if pressed_button == 2:
            center, rotation, originalXScale, originalYScale = \
                self.layer.transformParameters()
            number = '{}, {}'.format(originalXScale, originalYScale)
            number, ok = QInputDialog.getText(
                None, u'Scale', u'Scale (x,y) or scale/(dpi/2.54)', text=number)
            if ok:
                scales = number.split(',')
                if len(scales) > 2:
                    QMessageBox.information(self.iface.mainWindow(),
                                     u'Error',u"Must be two numbers")
                    return
                if len(scales) == 1:
                    if is_formula(scales[0]):
                        scales[0] = eval(scales[0])
                    xScale = float(scales[0])
                    yScale = xScale
                else:
                    if is_formula(scales[0]):
                        scales[0] = eval(scales[0])                    
                    if is_formula(scales[1]):
                        scales[1] = eval(scales[1])                    
                    xScale = float(scales[0])
                    yScale = float(scales[1])
                self.isEmittingPoint = False

                self.rubberBandExtent.reset(QGis.Line)
                self.rasterShadow.reset()

                
                self.layer.setScale(xScale, yScale)

            self.layer.repaint()

            self.layer.commitTransformParameters()

**Comment by gvellut** [comment]
Thank you. I have merged your patch. I changed it a little so that only the scale factor (e.g. 12000) and the DPI have to be entered (and the computed formula is implicit i.e.  scale/(dpi/0.002.54)). Later, I intend to modify the property dialog to allow explicit setting of the parameters (including xscale and yscale).
