### ISSUE TITLE
Error in exporting raster with world file

### ISSUE THREAD

**Issue by tbrauning** [gvellut/FreehandRasterGeoreferencer#12]
I have geolocated an image and want to export it with georeferencing information so that I can change my map CRS. When I click the !! button and choose a file location I get the following error:
TypeError("QImage.fill(int): argument 1 has unexpected type 'QColor'",)
My image is a png with alpha channel.

**Comment by gvellut** [comment]
What version of the plugin do you have installed ?
If you are on version 0.5.x.1, did you check the checkbox in the export dialog ?

**Comment by tbrauning** [comment]
0.5.2
There is no checkbox
Yes, PNG
I see there is now 0.5.2.1 - I will try that.

**Comment by tbrauning** [comment]
0.5.2.1 worked - thank you for your essential plugin and quick response!

**Comment by gvellut** [comment]
OK great.
