### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by fgfletcher** [gvellut/FreehandRasterGeoreferencer#14]
Wonderfully useful plugin!  Many thanks!   A few suggestions:
1) Documentation: "“Uniform scale” mode is available by using the Ctrl modifier" -  on Macs uses Cmd (apple) key while Ctrl key is used for "right click".
2) Undo of last step - would be especially helpful when I forget to use Uniform Scale!
3) "Crop sides" - to reduce area of plan that is displayed, e.g., to exclude title strip or notes column from a plan being georeferenced.  Similar to "adjust" except would not scale, just crop.
Cordially,
Garth Fletcher

**Comment by gvellut** [comment]
Thank you for your feedback.

1. You are right. I will fix that and change the modifier for Macs.
2. Currently, I don't plan on adding that but I will gladly accept a patch that adds the feature.
3. Currently not in the plan and I don't think I want to add it. I think an image editor could be used to perform  crop before importing the image with the plugin.

I have added separate issues in the tracker for 1 and 2.
