### ISSUE TITLE
Add image with map scale and dpi

### ISSUE THREAD

**Issue by tmizu23** [gvellut/FreehandRasterGeoreferencer#18]
I want to add the scanned map it has map scale and resolution. 
If you can specify the scale and resolution, the map size can be calculated correctly. 
And you only need to fine-tune.

The map scale is like 25000. (it means 1:25000)
The resolution means dpi.

**Comment by Dkrav-UA** [comment]
[http://gvellut.github.io/FreehandRasterGeoreferencer/](http://gvellut.github.io/FreehandRasterGeoreferencer/)
scale part of documentation.

**Comment by tmizu23** [comment]
Thank you. I did not notice.
