### ISSUE TITLE
Scale.

### ISSUE THREAD

**Issue by Dkrav-UA** [gvellut/FreehandRasterGeoreferencer#2]
Hi. Plugin is great.
IMHO Scale is better with constrain proportions.
Uniform Scale is done with Adjust sides.

**Comment by DAW93** [comment]
Agreed - it would be nice to have a locked ratio. Great stuff though.

**Comment by Oreonax** [comment]
+1 plugin is great for fast georeferencing. Constrain proportions would be soo awesome !

**Comment by Dkrav-UA** [comment]
If you need constrain proportions replace file freehandrastergeoreferencer_maptools.py
[freehandrastergeoreferencer_maptools.zip](https://github.com/gvellut/FreehandRasterGeoreferencer/files/385689/freehandrastergeoreferencer_maptools.zip)

**Comment by Oreonax** [comment]
Thanks. Works perfectly !

**Comment by DAW93** [comment]
I replaced the file with the one you provided but the constrain proportions is still not working. Am I missing a step?

**Comment by Dkrav-UA** [comment]
Make sure that the changed file in the plugin directory.

**Comment by DAW93** [comment]
Figured it out thanks! I had accidentally reinstalled the default... oops

**Comment by gvellut** [comment]
Thanks. In version 0.3.0, it has been added as an option (using Ctrl with the Scale tool)
