### ISSUE TITLE
pdf support

### ISSUE THREAD

**Issue by tmizu23** [gvellut/FreehandRasterGeoreferencer#24]
I would like to add PDF.
So I work in progress.

**Comment by tmizu23** [comment]
support adding pdf.
I get a crs warning when adding pdf, please ignore.
It does not support export as pdf.

@gvellut 
A series of my work is finished. If there is no problem, will you release a plugin?

**Comment by gvellut** [comment]
Thank you. I will test all the changes and make a new release most likely by tomorrow.
