### ISSUE TITLE
Location of image path

### ISSUE THREAD

**Issue by arend64** [gvellut/FreehandRasterGeoreferencer#28]
For a reason not clear to me, but probably related with my efforts to move rasters to a faster drive, FreehandRasterGeoreferencer does not display these rasters anymore, even so after placing the rasters back to the original folder. Probably the registration of the ImagePath is messed up, or at least wrong

My basic question is, what can I do to see these rasters again in QGIS.
Probably related questions are; where and how does FreehandRasterGeoreferencer store the ImagePath, and can (if so, how) this ImagePath be edited ?

**Comment by Dkrav-UA** [comment]
There are different files with georeferencing data, depending on what raster format you use. 
*.wld files are for all files (tiff, jpg, png, ...)
*.pgw for png
*.tfw for tif
*.jgw for jpg
you need both files in same dir for raster to be georeferenced. 

P.S. Tiff file may have georeferencing tags in it.

**Comment by gvellut** [comment]
Normally, if your image is at the same directory as the .QGS file or below, the path saved inside the .QGS is relative to the directory of the .QGS file (one caveat is that the .QGS file must exist on the file system at the time the image is added). So if you move **both** the .QGS and the images, the path will stay valid. Is your issue related to that ? 

If the image cannot be found when the .QGS project is opened, there should be a dialog to ask you where to find it. You can update the path there (you will also need to save the .QGS again after loading so the new path is saved). Did you get this dialog ?

You can change the image path manually inside the .QGS :

If you open the .QGS file in a text editor, you can find the image path stored inside a custom property below the maplayer XML element corresponding to the FreehandRasterGeoreferencer layer : 

```xml
<maplayer type="plugin" name="FreehandRasterGeoreferencerLayer">
```

Below this you will have some custom properties and the file path is stored inside the property with key "filepath" :

```xml
<customproperties>
        ...
        <property value="/Users/guilhem/Documents/gis/frgf_test/H3EUV4Q.jpg" key="filepath"/> 
        ...
 </customproperties>
```
