### ISSUE TITLE
QGIS 3.8 gives warning about setTransformContext not being implemented

### ISSUE THREAD

**Issue by jaminmelville** [gvellut/FreehandRasterGeoreferencer#30]
On opening a QGIS project file that has existing FreehandRaster layers in QGIS 3.8 I get the following warning showing up in logs:

```
"NotImplementedError: QgsPluginLayer.setTransformContext() is abstract and must be overridden" 
```

I've tried to implement by adding the following into the `FreehandRasterGeoreferencerLayer` class:

```
    def setTransformContext(self, transformContext):
        self.provider.setTransformContext(transformContext)
```

but noticed the [API](https://qgis.org/api/classQgsDataProvider.html#af36b4c59d0970126bfa9070b9f425212) has a note saying "not available in python bindings" for the provider class.

I'm not sure where to go from here. If someone could point me in the right direction I'm happy to submit a pull request.

**Comment by gvellut** [comment]
Thank you for your feedback. I will have a look. 

I haven't used the plugin in a long time but I also get this error when trying to load an image on QGIS 3.8.0 on macOS. In any case, it seems that if you dismiss the dialog, after that, there is no impact on the functionality of the plugin. Is that also the case for you ?

It seems related to this relatively recent patch https://github.com/qgis/QGIS/pull/9627 Unfortunately, this kind of things also happened with 3.4 when a refactoring on Map layers is made and no thought seems to be given to plugin layers (which I guess are relatively uncommon).

**Comment by gvellut** [comment]
@jaminmelville I have made a new release: It adds a setTransformContext method that does nothing (pass) and it seems to prevent the error dialog from appearing. Let me know if you encounter additional issues.

**Comment by jaminmelville** [comment]
Thanks @gvellut 👍 nice solution 😆 I'll let you know if anything else pops up ✅
