### ISSUE TITLE
Problems loading tif file

### ISSUE THREAD

**Issue by JohanRaniseth** [gvellut/FreehandRasterGeoreferencer#31]
I'm having trouble loading a tif file. When loaded normally like a raster in Qgis it looks like this(with hillshading).
<img width="669" alt="QgisProblem" src="https://user-images.githubusercontent.com/31434181/74387456-db053080-4df8-11ea-8ecf-72ccb097fea1.png">

When loading it with Freehand these are the properties of the layer. It looks like it somehow stops/can't read it and just sets the width and height to 0. Also, the X,Y center seems to be at the top left of the tif file. Got any tips or possible solutions?
<img width="336" alt="QgisProblem2" src="https://user-images.githubusercontent.com/31434181/74387553-228bbc80-4df9-11ea-9818-e0aa2b808c9b.png">

**Comment by Dkrav-UA** [comment]
Try to convert raster with QGIS. With correct CRS. Maybe something missing in tif tags.

**Comment by gvellut** [comment]
Can you send me the file? Or preferably only a small clip (if it has the same issue). 
What is its original resolution?
Can you also tell me your OS and QGIS version ?

I will have a look.

**Comment by JohanRaniseth** [comment]
It is quite a large file at 58MB. Resolution is around 3700x3700.  I'm using Windows 10 and QGIS is 3.10.2.
My hope was to use the Freehand tool to shift my two rasters from an aerial survey with "bad" GPS coordinates so they overla. So that I could then clip them into smaller pairs of the rasters to use for machine learning.

I couldn't upload the file here due to size so I uploaded it to mega.
https://mega.nz/#!QdIAXChb

**Comment by JohanRaniseth** [comment]
Also, can't see anything that strikes me as wrong with the CRS of the tif.
CRS	EPSG:32632 - WGS 84 / UTM zone 32N - Projected

**Comment by Dkrav-UA** [comment]
This is QImageReader problem. It gives the wrong image dimensions. 
As a workaround, you can use gdal tools to remove the georeference information (gdal_edit).
And then move an image in tfw file.
[DEM_geotif.zip](https://github.com/gvellut/FreehandRasterGeoreferencer/files/4198232/DEM_geotif.zip)

**Comment by JohanRaniseth** [comment]
Thank you I'll try that!

**Comment by Dkrav-UA** [comment]
The problem is in the DEM file. It contains floating-point information for every pixel. 
If you need to visually move the image, then you need to convert it to a "standard" format.
gdal_translate -of JPEG -scale -co worldfile=yes DEM_geotif.tif  output.jpg
That file you can move with this plugin.
[output.zip](https://github.com/gvellut/FreehandRasterGeoreferencer/files/4198484/output.zip)

**Comment by JohanRaniseth** [comment]
I can't load tfw files it seems. I'm sorry but I'm quite new to Qgis and how all the tools work. 
I'm suppose to remove the georeference information by doing something like: gdal_edit -unsetgt DEM_geotif.tif.
And then I open the tif file in Qgis, and move it to a tfw file? 
Or should I be able to open the edited DEM_geotif.tif Freehand after doing the gdal_edit?

**Comment by Dkrav-UA** [comment]
No. Tfw file contains georeference infirmation. You need to change base coordinates in a text editor. And than reopen tif file in qgis.

**Comment by JohanRaniseth** [comment]
I will attempt again when I get home. Do you by any chance know of any other tool where you can click on one point from two rasters and then they shift so the points overlap based on those two points you selected?

**Comment by JohanRaniseth** [comment]
Thank you so much Dkrav! Freehand loaded the output.jpg that was generated with gdal_translate very nicely. But is there any way of getting hillshading on the Freehand object? Doing the referencing without it is gonna be near impossible. I can't find any option for it but it couldn't hurt asking.

**Comment by Dkrav-UA** [comment]
You can place output.jpg. And then use its georeferece in "wld" file for your hillshade.
