### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'center'

### ISSUE THREAD

**Issue by bkmeneguello** [gvellut/FreehandRasterGeoreferencer#32]
* Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
* QGIS: 3.10.6-A Coruña A Coruña, ec80021f49 

The error happens with the "Georeference raster with 2 points", when I click the first point.

I have two layers, the top most is a shapefile and the botton is a raster image imported with the plugin.

```
Traceback (most recent call last):
  File "C:/Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer_maptools.py", line 636, in canvasPressEvent
    self.originalCenter = self.layer.center
AttributeError: 'NoneType' object has no attribute 'center'
```

Amazing plugin, by the way.

**Comment by bkmeneguello** [comment]
If the raster layer is the top most it works (most of the time - I saw the error once after change the layer order)

**Comment by gvellut** [comment]
Thank you.

I will have a look.
