### ISSUE TITLE
Transforming FreehandRasterGeoreferencer layer to an ”ordinary” layer

### ISSUE THREAD

**Issue by Forrestus** [gvellut/FreehandRasterGeoreferencer#33]
Unless I overlooked something, it's surprisingly difficult to transform FRG layer to a raster layer. It seems that the only way is to export the layer to .pgw and then to import it back to QGIS. However, the resolution of the imported file becomes very low (see screenshot).

<img width="795" alt="Normal FRG" src="https://user-images.githubusercontent.com/44900924/86477504-d827bf80-bd48-11ea-8c96-e5e434d54496.png">
<img width="807" alt="Exported and re-imported" src="https://user-images.githubusercontent.com/44900924/86477510-da8a1980-bd48-11ea-89c9-c9be3f081dbd.png">

**Comment by gvellut** [comment]
Did you check the "Put Rotation in World File" checkbox when you exported? This option should give you the same pixel content as the original file (rotation is put in the world file => may not work well on ArcGIS). Then when you reimport, QGIS will apply the rotation itself.

If this is not checked, the rotation is exported in the output file directly and the pixels are changed. Normally the resolution of the exported file should be the same or greater than the original file, but with the rotation, some of the details get lost. There is a render hint (SmoothPixmapTransform) that may help. If you want to try you can uncomment in the code of the plugin[ at this line](https://github.com/gvellut/FreehandRasterGeoreferencer/blob/master/freehandrastergeoreferencer_commands.py#L77) in your own local install. I really can't remember why it was commented out (maybe I meant to comment the other render hint...) but there is no better option I can see in QT (except to export a rotated image with a greater resolution than the original, which may be a choice to be added in the UI during the export, like a factor of the original resolution).

Let me know.

**Comment by gvellut** [comment]
On top of that, an option could also be added during the export to immediately add the exported file in QGIS. I can add an issue for that.

**Comment by Forrestus** [comment]
Thank you Guilhem! I tried exporting with rotation and without, I modified the code as you suggested and tried again with and without rotation. The result is still pixelated in the same way.
Am 3. Juli 2020, 18:18 +0200 schrieb Guilhem Vellut <notifications@github.com>:

**Comment by Forrestus** [comment]
The generated PNG is actually not pixelated (sorry, I should have tried earlier). So I think that the problem lies elsewhere. In general, I have problems with getting QGIS render map canvas and rasters in high resolution (I have a MacBook with retina display). Now, your plugin somehow manages miraculously to by-pass that problem and renders the rasters properly (congratulations). But once I export the rester outside of your HD paradise, it becomes as pixelated as the rest of the surroundings...

Now, I wish I could find a way to import your World Files to Google Earth, that would be great, but it's another topic.
Am 3. Juli 2020, 18:18 +0200 schrieb Guilhem Vellut <notifications@github.com>:

**Comment by gvellut** [comment]
The way it appears in your screenshot it might be an issue with the upsampling (zoomed out). Have you tried changing the setting in the raster symbology ?

<img width="588" alt="Screenshot 2020-07-03 at 20 18 14" src="https://user-images.githubusercontent.com/3685/86491239-87c15980-bd6a-11ea-969f-8d7cf056243c.png">

For Google Earth, you could use [gdal2tiles](https://gdal.org/programs/gdal2tiles.html) or compute yourself what is needed to generate a [GroundOverlay](https://developers.google.com/kml/documentation/kmlreference#groundoverlay)  based on the matrix in the .pgw (or maybe there is a plugin that does that).
