### ISSUE TITLE
Added layer has 0 width and 0 height

### ISSUE THREAD

**Issue by NicolasCadieux** [gvellut/FreehandRasterGeoreferencer#35]
When adding a layer in QGIS 3.14, layer is empty. 

![Capture](https://user-images.githubusercontent.com/1158162/96285540-1752e700-0fad-11eb-82e6-d095b66fbf2a.PNG)

**Comment by NicolasCadieux** [comment]
toto.tif file is made from this test asc file:
ncols 4
nrows 4
xllcorner 0
yllcorner 0
cellsize 1
nodata_value -9999
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16

**Comment by Toedi** [comment]
Got the same issue on 3.16 (tried also with 3.14)!
In my case the problem appears with orthomosaics created with Pix4DFields. Sometimes also with orthomosaics created with Dronedeploy.

View is zoomed onto issued layer. Normally it should be placed where the other activated layer can be seen partially (down right corner in my screenshot).

![bugreport](https://user-images.githubusercontent.com/20247879/97180109-f010cc80-1799-11eb-9ed9-1db04a00519d.png)

**Comment by Dkrav-UA** [comment]
Try a different image format. This is a QImage problem. Convert it to PNG or TIF with GDAL tools.

**Comment by Toedi** [comment]
Thanks for your fast answer.
Since my orthomosaics are already in TIF format i've tried converting it to PNG via GDAL Translate. Unfortunately I got the same issue.

I've got several orthomosaics which are already aligned propperly to my needs. My attempt would be to copy the geodata of those orthomosaics onto the new ones and hope that it somehow fits ^^. Could you provide a solution on how to do this?

**Comment by Dkrav-UA** [comment]
There are a couple of opportunities:
1. If QGIS shows your images you can use the standard tool Raster\Georeferencer.
2. Try to save image in 8bit grayscale. And then use this plugin.
3. With GDAL tools you can extract tfw/wld file from the georeferenced image and use this file with your image.

**Comment by Toedi** [comment]
Thanks a lot for your time and help, i really appreciate it! <3

For those who also got stuck, i've came up with even another solution which suited my workflow the most...
Since i did not need any rotation or rescaling I executed the accepted answer in this thread:

https://gis.stackexchange.com/questions/13561/how-to-translate-reposition-a-raster-in-python

Cheers

**Comment by NicolasCadieux** [comment]
Hi,
Are you saying that we can only use 8bit grey scale images with the plugin?
Nicolas

**Comment by Dkrav-UA** [comment]
No. Some images have non-standard color models. So QImage can't read it

**Comment by NicolasCadieux** [comment]
Ok thanks for the info.

**Comment by fgfletcher** [comment]
I have been using 1-bit PNG files from scanned survey maps.  Seems to accept that (very compact) format without issues.

**Comment by Dkrav-UA** [comment]
Rasters with transparency displayed very wrong.
![изображение](https://user-images.githubusercontent.com/16414895/107956876-7a2eac00-6fa8-11eb-97c7-e05de29146bb.png)

**Comment by gvellut** [comment]
Is that with the just released version ? Which format is the raster (PNG, TIFF... )?

**Comment by Dkrav-UA** [comment]
PNG and TIF.  Standard  4-band RGBA
![изображение](https://user-images.githubusercontent.com/16414895/107963023-4fe0ec80-6fb0-11eb-8b1d-c6cef9405426.png)

**Comment by Dkrav-UA** [comment]
![main-part](https://user-images.githubusercontent.com/16414895/107963378-c2ea6300-6fb0-11eb-91c9-fec92fbf8c38.png)

**Comment by gvellut** [comment]
OK thank you.

But is it with the version of the plugin I just released ? Or some version in the repository ?

**Comment by Dkrav-UA** [comment]
![изображение](https://user-images.githubusercontent.com/16414895/107963863-59b71f80-6fb1-11eb-9bdc-0f6f1408c7b7.png)

**Comment by gvellut** [comment]
OK I see. Thank you.

**Comment by gvellut** [comment]
I have uploaded a new version that should correct the issue you had.

**Comment by Dkrav-UA** [comment]
Seems to be ok.

**Comment by gvellut** [comment]
Great. Thanks again for you help.
