### ISSUE TITLE
Rotation entry and report limited to 0.1°, i.e., nnn.n.  Would like more, e.g., nnn.nnn

### ISSUE THREAD

**Issue by fgfletcher** [gvellut/FreehandRasterGeoreferencer#36]
QGIS 3.16.2 running on Mac OS X 10.13.6.
Can only manually enter rotation with 0.1° resolution, though Rotate tool allows much finer adjustment. Similarly, the Properties (double click on layer) only reports the actual rotation rounded to 0.1° resolution.
It would be very useful to have higher resolution, both for manual entry and in the Properties report.

A VERY useful plug-in which I use frequently for aligning survey plats into a map.
Many thanks!

**Comment by gvellut** [comment]
Thank for your feedback. I will change it.
