### ISSUE TITLE
Loaded tif image is a dark box

### ISSUE THREAD

**Issue by Ggs1mida** [gvellut/FreehandRasterGeoreferencer#38]
I add a tif image but the result is a dark box, there is no texture shown.
![QXE{A KS@N}MF NIW ELM7J](https://user-images.githubusercontent.com/32317924/106236513-0d0ad080-61cb-11eb-99ce-c2308bb3b162.png)

**Comment by Dkrav-UA** [comment]
Show the info about your tiff image (color scheme etc.)

**Comment by Ggs1mida** [comment]
![_AO70KP$Z62NJX7UR Z{_PL](https://user-images.githubusercontent.com/32317924/106335882-abdf0d80-625b-11eb-9f7e-7fa279e01f86.png)
![E9MXZNU D GI0F_5_KBDVBT](https://user-images.githubusercontent.com/32317924/106335916-bef1dd80-625b-11eb-9628-443f2452fb15.png)

**Comment by Ggs1mida** [comment]
i am not sure if it is enough

**Comment by Dkrav-UA** [comment]
You have the wrong CRS inside your file. Try to change CRS in QGIS. It seems you need to set 3857(pseudo-mercator). 
The image is not big. So if it is possible upload it here.

**Comment by robmarkcole** [comment]
I have the same issue with a geotiff that is greyscale image with `int16` data type. The screenshot below shows the image (top) imported via this plugin and (bottom) just imported regularly

![image](https://user-images.githubusercontent.com/11855322/106597401-471efe00-654e-11eb-9d91-de2497fc8311.png)
