### ISSUE TITLE
Unable to load tiff

### ISSUE THREAD

**Issue by robmarkcole** [gvellut/FreehandRasterGeoreferencer#39]
I wish to register this tiff, which imports without issue into QGIS. However when I use this plugin it is unable to load the tiff, with the file just appearing greyed out. Since the file extension is valid I would expect the load to begin and then error if there were some issue with the file itself.

![image](https://user-images.githubusercontent.com/11855322/106579619-cf92a400-6538-11eb-8c7c-cfee7388b0ec.png)

**Comment by gvellut** [comment]
I think the extension must be .tif (instead of .tifF). But I will add the support for the .tiff extension.

**Comment by robmarkcole** [comment]
@gvellut  I can confirm on changing the file extension to `.tif` it is loaded successfully

**Comment by robmarkcole** [comment]
@gvellut would you mind doing a release so I can try this out?

**Comment by gvellut** [comment]
I will try to do a release tomorrow.

**Comment by gvellut** [comment]
I have made a release (version 0.8.0). Let me know if you encounter issues.
