### ISSUE TITLE
Plugin error on a Linux build

### ISSUE THREAD

**Issue by zeddock** [gvellut/FreehandRasterGeoreferencer#43]
I am on Manjaro Linux with QGIS 3.20.0
I get this error when installing from zip:
Couldn't load plugin 'FreehandRasterGeoreferencer-master' due to an error when calling its classFactory() method 

ImportError: cannot import name 'resources_rc' from 'FreehandRasterGeoreferencer-master' (/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer-master/__init__.py) 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer-master/__init__.py", line 24, in classFactory
    from .freehandrastergeoreferencer import FreehandRasterGeoreferencer
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer-master/freehandrastergeoreferencer.py", line 19, in 
    from . import resources_rc  # noqa
ImportError: cannot import name 'resources_rc' from 'FreehandRasterGeoreferencer-master' (/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/FreehandRasterGeoreferencer-master/__init__.py)

Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0] 
QGIS version: 3.20.0-Odense Odense, exported 

Python Path:
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LAStools
/usr/share/qgis/python
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/usr/lib/python3.9/site-packages
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/libs
![QGIS Plugin Error](https://user-images.githubusercontent.com/26576089/128206170-e2ee8673-08a2-4735-9f2f-e71268ffb8cb.png)

**Comment by gvellut** [comment]
Thank you for your bug report.

How did you install the plugin ? Through the QGIS Plugin Manager or with a clone of the repo ?

If you have cloned the repo, you will need to generate a few Python files, using the `build.sh` script (you will need the pyrcc5 and pyuic5 tools).

**Comment by zeddock** [comment]
I downloaded the zip and installed form zip

I am not familiar with the build.sh.   Can you point me toward a tutorial or give me the steps please?

Thank you.

**Comment by zeddock** [comment]
I see it was closed.

What was the issue? Or is it just resolved from some other update being
done?

Thank you.

Jim

...sent from my scrawney phone. please forgive typos...
