### ISSUE TITLE
ModuleNotFoundError: No module named 'FreehandRasterGeoreferencer-0'

### ISSUE THREAD

**Issue by rotornut44** [gvellut/FreehandRasterGeoreferencer#44]
Hello,
I updated QGis to v3.20.1 on the 31st of last month. I successfully installed and used your plugin on that same day. However, after a few weeks of not using the program, I loaded it up today to find that your plugin was no longer installed and all of my XYZ Tile servers were wiped.

I set everything back up, but when I install your plugin (I used the release version, both times, not the repo), it fails to load and throws the error seen below.. Any ideas as to why this might have suddenly started happening?

`Couldn't load plugin 'FreehandRasterGeoreferencer-0.8.3' 

ModuleNotFoundError: No module named 'FreehandRasterGeoreferencer-0' 
Traceback (most recent call last):
  File "F:\programs/QGIS 3.20.1/apps/qgis/./python\qgis\utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "F:\programs/QGIS 3.20.1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'FreehandRasterGeoreferencer-0'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.1-Odense Odense, 1c3c5cd6 

Python Path:
F:/programs/QGIS 3.20.1/apps/qgis/./python
C:/Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
F:/programs/QGIS 3.20.1/apps/qgis/./python/plugins
F:\programs\QGIS 3.20.1\bin\python39.zip
F:\programs\QGIS 3.20.1\apps\Python39\DLLs
F:\programs\QGIS 3.20.1\apps\Python39\lib
F:\programs\QGIS 3.20.1\bin
F:\programs\QGIS 3.20.1\apps\Python39
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages\win32
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages\win32\lib
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python`

Here's the python error log as well:
`2021-08-15T15:51:48     CRITICAL    Traceback (most recent call last):
File "F:\programs/QGIS 3.20.1/apps/qgis/./python\qgis\utils.py", line 313, in loadPlugin
__import__(packageName)
File "F:\programs/QGIS 3.20.1/apps/qgis/./python\qgis\utils.py", line 799, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'FreehandRasterGeoreferencer-0'`

Thanks!

**Comment by gvellut** [comment]
The "Couldn't load plugin 'FreehandRasterGeoreferencer-0.8.3'" bit is weird. Did you install using the plugin manager or some other method ? Normally, with the plugin manager it should install in a folder simply called "FreehandRasterGeoreferencer" (without the version)

The problem is "FreehandRasterGeoreferencer-0.8.3" is not a valid Python module name (because of the dots '.', which are normally used for separating submodules). This is maybe why you get the error at the end "No module named 'FreehandRasterGeoreferencer-0'" (withouth the '.8.3') because the dots '.' are interpreted as Python module path separators and that particular folder 'FreehandRasterGeoreferencer-0' indeed does not exit.

**Comment by rotornut44** [comment]
Hello,
I downloaded the release version here on GitHub. I extracted the zip, renamed the folder, and rezipped and that took care of the above issue. However, I now have another issue which I am getting with both the GitHub release and master branch. I'll include the error below if you wish to investigate more.

However, I just happened to remember that your plugin is on the Qgis plugin repository. I'm thinking now that's probably where I got it from, as I didn't have any of these issues just a few weeks ago. And obviously, the GitHub version hasn't been updated since then, so I should have had these issues then as well.

Installing from the Qgis repository, the plugin is working just fine.


**Plugin Install Error Log:**
Couldn't load plugin 'FreehandRasterGeoreferencer' due to an error when calling its classFactory() method 

ImportError: cannot import name 'resources_rc' from 'FreehandRasterGeoreferencer' (C:\Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FreehandRasterGeoreferencer\__init__.py) 
Traceback (most recent call last):
  File "F:\programs/QGIS 3.20.1/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FreehandRasterGeoreferencer\__init__.py", line 24, in classFactory
    from .freehandrastergeoreferencer import FreehandRasterGeoreferencer
  File "F:\programs/QGIS 3.20.1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer.py", line 19, in 
    from . import resources_rc  # noqa
ImportError: cannot import name 'resources_rc' from 'FreehandRasterGeoreferencer' (C:\Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FreehandRasterGeoreferencer\__init__.py)


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.1-Odense Odense, 1c3c5cd6 

Python Path:
F:/programs/QGIS 3.20.1/apps/qgis/./python
C:/Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
F:/programs/QGIS 3.20.1/apps/qgis/./python/plugins
F:\programs\QGIS 3.20.1\bin\python39.zip
F:\programs\QGIS 3.20.1\apps\Python39\DLLs
F:\programs\QGIS 3.20.1\apps\Python39\lib
F:\programs\QGIS 3.20.1\bin
F:\programs\QGIS 3.20.1\apps\Python39
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages\win32
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages\win32\lib
F:\programs\QGIS 3.20.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/christopherbritton.CHRISTOPHERBRIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by gvellut** [comment]
The code on Github (from which the release ZIP is automatically generated) doesn't include some files that need to be compiled to Python. Hence the errors you see. That compilation is done before uploading to the QGIS plugin repository (so the ZIP there has everything needed to run).

I guess you don't need it now but to build the missing Python files, the instructions are on the README : https://github.com/gvellut/FreehandRasterGeoreferencer#from-github
