### ISSUE TITLE
Freehand raster georeferencer plugin creates a border around every image

### ISSUE THREAD

**Issue by IAmHereAtGithub** [gvellut/FreehandRasterGeoreferencer#46]
Sorry if this is an obvious configuration settings somewhere, but I spend hours and can´t solve it.

I installed latest ubuntu and qgis.
Every time I add a image with the "Freehand raster georeferencer" plugin I get a border around the image, and I see no possibility to remove this border.

![qgis](https://user-images.githubusercontent.com/89143144/132706322-d8fc8d01-b2c5-44f4-b744-dec72fa885e6.png)

Steps to reproduce the issue
Install "Freehand raster georeferencer" plugin.
Create new project.
Click on Layer > Add Layer > Add raster for inactive georeferencing.
Select any image (.png) you want and click on "Add New".

Versions
QGIS version
3.20.2-Odense

Freehand raster georeferencer
Installed version 0.8.3

**Comment by gvellut** [comment]
Yes the border is normal. I guess it could be a setting.

If you want the georefrerenced raster without the border, you should export it to a standard raster using the `!!` button then reimport the resulting file into QGIS (then you can remove the Freehand Georeferencer layer).

**Comment by IAmHereAtGithub** [comment]
!!! Thank you very much !!!
This "workaround" works.

But I am a still confused, because I work with QGIS (on windows) now over a year, and this border appears first time last week.
This was the reason for me to install an ubuntu on hyper-v with qgis. And for me it was very strange to see that this border appears there too, and I can´t find any configuration to remove it.
Right now, I can live with the export/import solution.

**Comment by jhuyn8** [comment]
freehandrastergeorefencer_layer.py from plugin directory. Comment out line#630. 

`# painter.drawRect(rect)`

tips: 
- look at few lines above and adjust settings for the border if you want a border but not as bold.
- you can unload the plugin via the plugin manager. save changes in the .py. then reload the plugin without restarting QGIS.

**Comment by nickskelton2** [comment]
If using the export then re-import method the resolution is very poor. 
The resolution with the black bound box is very good, but I can't have the black bounding box on the maps. 

I tried the .py method but could not install from new zip. possibly my error as I have never done that before. 

Any other workaround would be great. 

Thanks in advance
