### ISSUE TITLE
Cancel button and others requests

### ISSUE THREAD

**Issue by ArnoGitHub** [gvellut/FreehandRasterGeoreferencer#9]
- This plugin is really useful but it would be really helpful to provide a button that allow to reverse the previous action(s).

- Also, if possible it could really interesting to provide a way to define specific values for the translations, rotation and scale.

- Finally, could it be possible to define specific value for the extent of the Virtual Raster created (for example the extent of a layer already occurring in the project (for example allowing to set the Virtual Raster to the exact same extent of another raster already used in the project)

**Comment by gvellut** [comment]
Thank you for your feedback.

- For the first point, I don't plan on adding the feature but a patch is welcome.
- For the third point, it is not in the works either. A workaround could to be to zoom on the layer you want. Then when you add the raster with the plugin, the image will be centered by default on the zoomed extent. 
- For the second point, it is on my roadmap although I haven't got around to doing it. I have opened an enhancement issue with just this.

**Comment by gvellut** [comment]
The Undo feature has been added by @tmizu23  in version v0.6.3.0
